version: "2.1"
services:

############################################################################
# This container provides the network stack for all the sensitive          #
# containers.                                                              #
#                                                                          #
#                                                                          #
############################################################################
    vpn:
        image: frankwoodall/openvpn
        cap_add:
            - NET_ADMIN
        dns: 
            - 8.8.8.8
        restart: always
        devices:
            - /dev/net/tun
        volumes:
            - /opt/config/openvpn:/config
            - /etc/localtime:/etc/localtime:ro


    nzbget:
        image: linuxserver/nzbget
        restart: always
        depends_on:
            - vpn
        environment:
            - PUID=5005
            - PGID=1002
        volumes:
            - /downloads:/downloads
            - /opt/config/nzbget:/config
            - /mnt/storage:/storage
            - /etc/localtime:/etc/localtime:ro
        network_mode: "service:vpn"


    sonarr:
        image: linuxserver/sonarr
        restart: always
        depends_on:
            - vpn
        environment:
            - PUID=5005
            - PGID=1002
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /opt/config/sonarr/config.xml:/config/config.xml
            - /opt/appdata/sonarr:/config
            - /mnt/storage:/storage
            - /downloads:/downloads
        network_mode: "service:vpn"


    radarr:
        image: linuxserver/radarr
        restart: always
        depends_on:
            - vpn
        environment:
            - PUID=5005
            - PGID=1002
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /opt/config/radarr/config.xml:/config/config.xml
            - /opt/appdata/radarr:/config
            - /mnt/storage:/storage
            - /downloads:/downloads
        network_mode: "service:vpn"


############################################################################
# This is an nginx reverse proxy which allows local management of the      #
# containers on the vpn network.                                           #
#                                                                          #
#                                                                          #
############################################################################
    proxy:
        image: nginx
        restart: always
        links:
            - vpn:nzbget
            - vpn:sonarr
            - vpn:radarr
            - plex:plex_cont
        ports:
            - 80:80
            - 443:443
        volumes:
            - /opt/config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - /opt/config/nginx/conf.d:/etc/nginx/conf.d
            - /home/morpheus/dev/docker_images/letsencrypt/archive/frankw.us/:/certs
            - /etc/localtime:/etc/localtime:ro


    plex:
        image: linuxserver/plex
        restart: always
        hostname: nemesis        
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /opt/config/plex/Preferences.xml:/config/Library/Application Support/Plex Media Server/Preferences.xml
            - /opt/appdata/plex:/config
            - /mnt/storage:/data
        environment:
            - PUID=5005
            - PGID=1002  
            - VERSION=latest
        ports:
            - 32400:32400


############################################################################
# Interesting stats and analytics on plex usage.
#
#
#
############################################################################
    plexpy:
        image: linuxserver/plexpy
        restart: always
        volumes:
            - /opt/config/plexpy/config.ini:/config/config.ini
            - /opt/appdata/plexpy:/config
            - /etc/localtime:/etc/localtime:ro
            - /opt/appdata/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
        environment:
            - PUID=5005
            - PGID=1002


############################################################################
# Allow plex users to make content requests.
#
#
#
############################################################################
    ombi:
        image: linuxserver/ombi
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /opt/appdata/ombi:/config
            - /mnt/storage:/storage
        environment:
            - PUID=5005
            - PGID=1002

